installations:
    cask: [evernote, webcatalog, flux, avast-mac-security, slack, gitter, discord, teamviewer, skype, google-chrome, firefox, sequel-pro, dash, zeplin, postman, vlc, spotify, recordit, visual-studio-code, visual-studio-code]
configurations: null
symlinks: null
